import React from "react";
import "./App.css";
import HeaderContainer from "./components/Header/HeaderContainer";
import StickyHeader from "./components/Header/StickyHeader";
import PreviousOperations from "./components/PreviousOperations";
import MostRecentAlerts from "./components/MostRecentAlerts";
import OperationSwordsOfIron from "./components/OperationSwordsOfIron";
import OperationLionsRoar from "./components/OperationLionsRoar";
import RecentAlertsMap from "./components/RecentAlertsMap";
import Footer from "./components/Footer";
import FAQ from "./components/FAQ";
// import Social from "./components/Social";
import AlertClient from "./rocket_alert_client";
import { Row, Col } from "antd";
import RealTimeAlertManager from "./realtime_alert_manager";
import Utilities from "./utilities/utilities";
import Tracking from "./tracking";
import { getNow, get24HoursAgo, get48HoursAgo } from "./utilities/date_helper";
// import TimeToShelter from "./components/TimeToShelter";
import SupportUs from "./components/SupportUs";

class App extends React.Component {
  state = {
    alerts: {},
    showStickyHeader: false,
    // Whether query string alert mode param is set
    isAlertModeOverride: false,
    // Whether the app currently receives incoming alerts
    isAlertMode: false,
    // Whether this is the last real-time alert of the alert batch
    isLastAlertOfBatch: false,
    // The alert object
    realTimeAlert: null,
    // Alerts from 24 and up to 48 hours ago
    alerts48HrsAgo: [],
    // Most recent alerts (since the last history sync)
    mostRecentAlerts: [],
    // Real-time alerts that have been triggred since the last history sync
    realTimeAlertCache: { alerts: [], count: null },
    // Text when sharing on twitter. Generated in Header
    twitterShareText: "",
    // The location to focus on on the map
    mapFocus: null,
  };

  alertEventSource = null;

  componentDidMount() {
    RealTimeAlertManager.startRealTimeAlerts(
      AlertClient,
      this.processRealTimeAlert,
    );

    if (Utilities.isDev() && Utilities.isAlertModeQueryString()) {
      this.mockClientAlerts();
    }

    this.getMostRecentAlerts();

    window.addEventListener("scroll", this.handleScroll);
  }

  componentWillUnmount() {
    window.removeEventListener("scroll", this.handleScroll);
    RealTimeAlertManager.stopRealTimeAlerts();
  }

  /*
   * Gets alerts from the past 24 hours, local time.
   * If there are no alerts, returns null.
   */
  getMostRecentAlerts = () => {
    const dateTime24HrsAgo = get24HoursAgo();
    Promise.all([
      AlertClient.getMostRecentAlerts(get48HoursAgo(), dateTime24HrsAgo),
      AlertClient.getMostRecentAlerts(dateTime24HrsAgo, getNow()),
      AlertClient.getRealTimeAlertCache(),
    ])
      .then((values) => {
        const alerts48HrsAgo = values[0] ? values[0] : [];
        const mostRecentAlerts = values[1] ? values[1] : [];
        const realTimeAlertCache = values[2] ? values[2] : [];

        if (
          !alerts48HrsAgo &&
          !mostRecentAlerts &&
          realTimeAlertCache.count === 0
        ) {
          return;
        }

        this.setState({
          alerts48HrsAgo: alerts48HrsAgo.reverse(),
          mostRecentAlerts: [...mostRecentAlerts, ...realTimeAlertCache.alerts]
            .slice(-Utilities.MAX_RECENT_ALERTS)
            .reverse(),
          realTimeAlertCache,
        });
      })
      .catch((error) => {
        console.error(error);
        this.setState({ isError: true });
      });
  };

  /*
   * Mocks alerts in the client without hitting the server
   */
  mockClientAlerts = () => {
    const alerts = {
      alerts: [
        {
          name: "דליה",
          englishName: "Dalia",
          lat: 32.5892,
          lon: 35.077,
          taCityId: 1102,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ואדי ערה",
          areaNameEn: "Wadi Ara",
          timeStamp: "2026-02-28 11:13:22",
        },
        {
          name: "יקנעם המושבה והזורע",
          englishName: "Yokneam Moshava and HaZoreah",
          lat: 32.6559,
          lon: 35.1152,
          taCityId: 1138,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ואדי ערה",
          areaNameEn: "Wadi Ara",
          timeStamp: "2026-02-28 11:13:22",
        },
        {
          name: "יקנעם עילית",
          englishName: "Yokneam Illit",
          lat: 32.6602,
          lon: 35.1046,
          taCityId: 1137,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ואדי ערה",
          areaNameEn: "Wadi Ara",
          timeStamp: "2026-02-28 11:13:22",
        },
        {
          name: "מדרך עוז",
          englishName: "Midrach Oz",
          lat: 32.5946,
          lon: 35.158,
          taCityId: 1104,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ואדי ערה",
          areaNameEn: "Wadi Ara",
          timeStamp: "2026-02-28 11:13:22",
        },
        {
          name: "משמר העמק",
          englishName: "Mishmar HaEmek",
          lat: 32.6101,
          lon: 35.1427,
          taCityId: 1116,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ואדי ערה",
          areaNameEn: "Wadi Ara",
          timeStamp: "2026-02-28 11:13:22",
        },
        {
          name: "עין העמק",
          englishName: "Ein HaEmek",
          lat: 32.6297,
          lon: 35.0822,
          taCityId: 1132,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ואדי ערה",
          areaNameEn: "Wadi Ara",
          timeStamp: "2026-02-28 11:13:22",
        },
        {
          name: "עין השופט",
          englishName: "Ein HaShofet",
          lat: 32.5968,
          lon: 35.1004,
          taCityId: 1103,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ואדי ערה",
          areaNameEn: "Wadi Ara",
          timeStamp: "2026-02-28 11:13:22",
        },
        {
          name: "עמיקם",
          englishName: "Amikam",
          lat: 32.5646,
          lon: 35.0203,
          taCityId: 1089,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "מנשה",
          areaNameEn: "Menashe",
          timeStamp: "2026-02-28 11:13:22",
        },
        {
          name: "קיבוץ מגידו",
          englishName: "Kibutz Megiddo",
          lat: 32.5785,
          lon: 35.1805,
          taCityId: 1095,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ואדי ערה",
          areaNameEn: "Wadi Ara",
          timeStamp: "2026-02-28 11:13:22",
        },
        {
          name: "רמות מנשה",
          englishName: "Ramot Menashe",
          lat: 32.5966,
          lon: 35.0575,
          taCityId: 1101,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ואדי ערה",
          areaNameEn: "Wadi Ara",
          timeStamp: "2026-02-28 11:13:22",
        },
        {
          name: "רמת השופט",
          englishName: "Ramat HaShofet",
          lat: 32.6094,
          lon: 35.0941,
          taCityId: 1115,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ואדי ערה",
          areaNameEn: "Wadi Ara",
          timeStamp: "2026-02-28 11:13:22",
        },
        {
          name: "גבעת עוז",
          englishName: "Givat Oz",
          lat: 32.5559,
          lon: 35.198,
          taCityId: 1084,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ואדי ערה",
          areaNameEn: "Wadi Ara",
          timeStamp: "2026-02-28 11:13:22",
        },
        {
          name: "מעלה עירון",
          englishName: "Ma'aleh Iron",
          lat: 32.5541,
          lon: 35.1825,
          taCityId: 1075,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ואדי ערה",
          areaNameEn: "Wadi Ara",
          timeStamp: "2026-02-28 11:13:22",
        },
        {
          name: "חוף קליה",
          englishName: "Kalia Beach",
          lat: 31.7609,
          lon: 35.5027,
          taCityId: 2014,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ים המלח",
          areaNameEn: "Dead Sea",
          timeStamp: "2026-02-28 11:13:53",
        },
        {
          name: "אלון",
          englishName: "Alon",
          lat: 31.8334,
          lon: 35.3536,
          taCityId: 556,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "יהודה",
          areaNameEn: "Judea",
          timeStamp: "2026-02-28 11:13:53",
        },
        {
          name: "אלמוג",
          englishName: "Almog",
          lat: 31.79,
          lon: 35.462,
          taCityId: 499,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ים המלח",
          areaNameEn: "Dead Sea",
          timeStamp: "2026-02-28 11:13:53",
        },
        {
          name: "בית הערבה",
          englishName: "Beit HaArava",
          lat: 31.8078,
          lon: 35.4764,
          taCityId: 529,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ים המלח",
          areaNameEn: "Dead Sea",
          timeStamp: "2026-02-28 11:13:53",
        },
        {
          name: "ורד יריחו",
          englishName: "Vered Yericho",
          lat: 31.8262,
          lon: 35.4321,
          taCityId: 550,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ים המלח",
          areaNameEn: "Dead Sea",
          timeStamp: "2026-02-28 11:13:53",
        },
        {
          name: "מבואות יריחו",
          englishName: "Mevuot Yericho",
          lat: 31.9074,
          lon: 35.4156,
          taCityId: 1804,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "בקעה",
          areaNameEn: "Bika'a",
          timeStamp: "2026-02-28 11:13:53",
        },
        {
          name: "מצפה יריחו",
          englishName: "Mitzpeh Yericho",
          lat: 31.8157,
          lon: 35.3954,
          taCityId: 541,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "יהודה",
          areaNameEn: "Judea",
          timeStamp: "2026-02-28 11:13:53",
        },
        {
          name: "מרכז אזורי מגילות",
          englishName: "Megilot Regional Center",
          lat: 31.7738,
          lon: 35.5038,
          taCityId: 1716,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ים המלח",
          areaNameEn: "Dead Sea",
          timeStamp: "2026-02-28 11:13:53",
        },
        {
          name: "נעמה",
          englishName: "Na'ama",
          lat: 31.9076,
          lon: 35.4662,
          taCityId: 1805,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "בקעה",
          areaNameEn: "Bika'a",
          timeStamp: "2026-02-28 11:13:53",
        },
        {
          name: "קליה",
          englishName: "Kalia",
          lat: 31.7499,
          lon: 35.4661,
          taCityId: 444,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ים המלח",
          areaNameEn: "Dead Sea",
          timeStamp: "2026-02-28 11:13:53",
        },
        {
          name: "בית חגלה",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:53",
        },
        {
          name: "צומת אלמוג",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:53",
        },
        {
          name: "קדם ערבה",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:53",
        },
        {
          name: "עינות קדם",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:54",
        },
        {
          name: "ירושלים - מזרח",
          englishName: "Jerusalem - East",
          lat: 31.7627,
          lon: 35.2403,
          taCityId: 496,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירושלים",
          areaNameEn: "Jerusalem",
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "ירושלים - צפון",
          englishName: "Jerusalem - North",
          lat: 31.8211,
          lon: 35.2389,
          taCityId: 527,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירושלים",
          areaNameEn: "Jerusalem",
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "אזור תעשייה מישור אדומים",
          englishName: "Mishor Edomim Industrial Zone",
          lat: 31.7925,
          lon: 35.335,
          taCityId: 478,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "יהודה",
          areaNameEn: "Judea",
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "מעלה אדומים",
          englishName: "Ma'aleh Edomim",
          lat: 31.7774,
          lon: 35.298,
          taCityId: 454,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "יהודה",
          areaNameEn: "Judea",
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "קדר",
          englishName: "Kedar",
          lat: 31.7506435,
          lon: 35.3033842,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "כפר אדומים",
          englishName: "Kfar Edomim",
          lat: 31.8272,
          lon: 35.3372,
          taCityId: 540,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "יהודה",
          areaNameEn: "Judea",
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "עלמון",
          englishName: "Almon",
          lat: 31.8321,
          lon: 35.2968,
          taCityId: 549,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "יהודה",
          areaNameEn: "Judea",
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "אזור תעשייה שער בנימין",
          englishName: "Sha'ar Binyamin Industrial Zone",
          lat: 31.8654,
          lon: 35.2617,
          taCityId: 584,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שומרון",
          areaNameEn: "Samaria",
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "גבע בנימין",
          englishName: "Geva Binyamin",
          lat: 31.85,
          lon: 35.2739,
          taCityId: 565,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שומרון",
          areaNameEn: "Samaria",
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "ייט''ב",
          englishName: "Yitav",
          lat: 31.947215,
          lon: 35.422375,
          taCityId: 1837,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "בקעה",
          areaNameEn: "Bika'a",
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "מעלה מכמש",
          englishName: "Ma'aleh Michmash",
          lat: 31.8791,
          lon: 35.3059,
          taCityId: 1776,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שומרון",
          areaNameEn: "Samaria",
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "נערן",
          englishName: "Niran",
          lat: 31.9682,
          lon: 35.4539,
          taCityId: 1858,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "בקעה",
          areaNameEn: "Bika'a",
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "החווה של זוהר",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "נופי פרת",
          englishName: "Nofei Prat",
          lat: 31.8235,
          lon: 35.3199,
          taCityId: 539,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "יהודה",
          areaNameEn: "Judea",
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "בני אדם",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "חוות בניהו",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "חוות הרועה העברי",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "חוות חנינא",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "חוות ינון",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "חוות מלכיאל",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "חוות נחלת צבי",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "חוות צאן קדר",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "מגרון",
          englishName: "Migron",
          lat: 31.874167,
          lon: 35.259588,
          taCityId: 599,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שומרון",
          areaNameEn: "Samaria",
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "מצפה דני",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "מצפה חגית",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "נווה ארז",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "קדר דרום",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "רמת מגרון",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:13:56",
        },
        {
          name: "רימונים",
          englishName: "Rimonim",
          lat: 31.9354,
          lon: 35.3405,
          taCityId: 1823,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שומרון",
          areaNameEn: "Samaria",
          timeStamp: "2026-02-28 11:14:00",
        },
        {
          name: "אושה",
          englishName: "Usha",
          lat: 32.7965,
          lon: 35.1146,
          taCityId: 1319,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "המפרץ",
          areaNameEn: "HaMifratz",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "כפר המכבי",
          englishName: "Kfar HaMaccabi",
          lat: 32.7918,
          lon: 35.1148,
          taCityId: 1305,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "המפרץ",
          areaNameEn: "HaMifratz",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "רמת יוחנן",
          englishName: "Ramat Yochana",
          lat: 32.7935,
          lon: 35.1222,
          taCityId: 1306,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "המפרץ",
          areaNameEn: "HaMifratz",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "אעבלין",
          englishName: "Ibillin",
          lat: 32.8218,
          lon: 35.1901,
          taCityId: 1339,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "חמת גדר",
          englishName: "Hamat gader",
          lat: 32.6834,
          lon: 35.6647,
          taCityId: 1198,
          alertTypeId: 1,
          countdownSec: 15,
          areaNameHe: "דרום הגולן",
          areaNameEn: "Southern Golan",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "יודפת",
          englishName: "Yodfat",
          lat: 32.8366,
          lon: 35.2715,
          taCityId: 1355,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "כאוכב אבו אלהיג'א",
          englishName: "Kaukab Abu al-Hija",
          lat: 32.8319,
          lon: 35.2487,
          taCityId: 1354,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "מורשת",
          englishName: "Moreshet",
          lat: 32.8261,
          lon: 35.232,
          taCityId: 1348,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "קורנית",
          englishName: "Koranit",
          lat: 32.8444,
          lon: 35.2519,
          taCityId: 1361,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "אפיק",
          englishName: "Afik",
          lat: 32.7794,
          lon: 35.703,
          taCityId: 1314,
          alertTypeId: 1,
          countdownSec: 0,
          areaNameHe: "דרום הגולן",
          areaNameEn: "Southern Golan",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "אשדות יעקב",
          englishName: "Ashdot Yaacov",
          lat: 32.661,
          lon: 35.5798,
          taCityId: 1161,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "דרום הגולן",
          areaNameEn: "Southern Golan",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "בני יהודה וגבעת יואב",
          englishName: "Bnei Yehuda and Givat Yoav",
          lat: 32.7983,
          lon: 35.6911,
          taCityId: 1331,
          alertTypeId: 1,
          countdownSec: 15,
          areaNameHe: "דרום הגולן",
          areaNameEn: "Southern Golan",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "גינוסר",
          englishName: "Ginosar",
          lat: 32.8487,
          lon: 35.5232,
          taCityId: 1372,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "גליל תחתון",
          areaNameEn: "Lower Galilee",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "הררית יחד",
          englishName: "Hararit Yachad",
          lat: 32.8457,
          lon: 35.3693,
          taCityId: 1370,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "כפר חרוב",
          englishName: "Kfar Haruv",
          lat: 32.7624,
          lon: 35.6642,
          taCityId: 1289,
          alertTypeId: 1,
          countdownSec: 15,
          areaNameHe: "דרום הגולן",
          areaNameEn: "Southern Golan",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "מבוא חמה",
          englishName: "Mevo Hama",
          lat: 32.7367,
          lon: 35.6552,
          taCityId: 1257,
          alertTypeId: 1,
          countdownSec: 15,
          areaNameHe: "דרום הגולן",
          areaNameEn: "Southern Golan",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "נאות גולן",
          englishName: "Neot Golan",
          lat: 32.787,
          lon: 35.6932,
          taCityId: 1324,
          alertTypeId: 1,
          countdownSec: 15,
          areaNameHe: "דרום הגולן",
          areaNameEn: "Southern Golan",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "שער הגולן",
          englishName: "Sha'ar HaGolan",
          lat: 32.6869,
          lon: 35.6047,
          taCityId: 1197,
          alertTypeId: 1,
          countdownSec: 30,
          areaNameHe: "דרום הגולן",
          areaNameEn: "Southern Golan",
          timeStamp: "2026-02-28 11:14:46",
        },
        {
          name: "כוכב יעקב",
          englishName: "Kokhav Ya'akov",
          lat: 31.8803,
          lon: 35.2459,
          taCityId: 598,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שומרון",
          areaNameEn: "Samaria",
          timeStamp: "2026-02-28 11:14:57",
        },
        {
          name: "קריית אתא",
          englishName: "Kiryat Atta",
          lat: 32.8052,
          lon: 35.0925,
          taCityId: 1304,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "המפרץ",
          areaNameEn: "HaMifratz",
          timeStamp: "2026-02-28 11:14:57",
        },
        {
          name: "גשר",
          englishName: "Gesher",
          lat: 32.6212,
          lon: 35.5504,
          taCityId: 1135,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "בקעת בית שאן",
          areaNameEn: "Beit Sha'an Valley",
          timeStamp: "2026-02-28 11:14:57",
        },
        {
          name: "מנוף",
          englishName: "Manof",
          lat: 32.8533,
          lon: 35.2374,
          taCityId: 1366,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:14:57",
        },
        {
          name: "מצפה אבי''ב",
          englishName: "Mitzpeh Aviv",
          lat: 32.837951,
          lon: 35.201059,
          taCityId: 1353,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:14:57",
        },
        {
          name: "מרכז אזורי משגב",
          englishName: "Misgav Regional Center",
          lat: 32.8588,
          lon: 35.2598,
          taCityId: 1378,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:14:57",
        },
        {
          name: "רקפת",
          englishName: "Rakefet",
          lat: 32.8556,
          lon: 35.2642,
          taCityId: 1368,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:14:57",
        },
        {
          name: "שכניה",
          englishName: "Shekhanya",
          lat: 32.8492,
          lon: 35.2467,
          taCityId: 1367,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:14:57",
        },
        {
          name: "דיר חנא",
          englishName: "Deir Hanna",
          lat: 32.8623,
          lon: 35.3653,
          taCityId: 1381,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:14:57",
        },
        {
          name: "עראבה",
          englishName: "Arraba",
          lat: 32.8537,
          lon: 35.3372,
          taCityId: 1362,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:14:57",
        },
        {
          name: "אפק",
          englishName: "Afek",
          lat: 32.8383,
          lon: 35.1278,
          taCityId: 1352,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "גליל עליון",
          areaNameEn: "Upper Galilee",
          timeStamp: "2026-02-28 11:15:08",
        },
        {
          name: "עצמון - שגב",
          englishName: "Atzmon (Segev)",
          lat: 32.8658,
          lon: 35.2523,
          taCityId: 1385,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:15:08",
        },
        {
          name: "אזור תעשייה תרדיון",
          englishName: "Teradion Industrial Zone",
          lat: 32.8677,
          lon: 35.2731,
          taCityId: 1386,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:15:08",
        },
        {
          name: "אשבל",
          englishName: "Eshbal",
          lat: 32.877,
          lon: 35.306,
          taCityId: 1392,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:15:08",
        },
        {
          name: "בית סוהר צלמון",
          englishName: "Zalmon Prison",
          lat: 32.8717,
          lon: 35.4474,
          taCityId: 1931,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:15:08",
        },
        {
          name: "טפחות",
          englishName: "Tefahot",
          lat: 32.8686,
          lon: 35.4222,
          taCityId: 1387,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:15:08",
        },
        {
          name: "לבנים",
          englishName: "Livnim",
          lat: 32.8638,
          lon: 35.4975,
          taCityId: 1388,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "גליל תחתון",
          areaNameEn: "Lower Galilee",
          timeStamp: "2026-02-28 11:15:08",
        },
        {
          name: "מיצר",
          englishName: "Metzar",
          lat: 32.7686,
          lon: 35.7364,
          taCityId: 1290,
          alertTypeId: 1,
          countdownSec: 0,
          areaNameHe: "דרום הגולן",
          areaNameEn: "Southern Golan",
          timeStamp: "2026-02-28 11:15:08",
        },
        {
          name: "סכנין",
          englishName: "Sakhnin",
          lat: 32.8642,
          lon: 35.2945,
          taCityId: 1380,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "מרכז הגליל",
          areaNameEn: "Center Galilee",
          timeStamp: "2026-02-28 11:15:08",
        },
        {
          name: "ירושלים - אזור תעשייה עטרות",
          englishName: "Jerusalem - Atarot Industrial Zone",
          lat: 31.8606,
          lon: 35.2167,
          taCityId: 564,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירושלים",
          areaNameEn: "Jerusalem",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "ירושלים - דרום",
          englishName: "Jerusalem - South",
          lat: 31.7377,
          lon: 35.1847,
          taCityId: 415,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירושלים",
          areaNameEn: "Jerusalem",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "ירושלים - כפר עקב",
          englishName: "Jerusalem - Qafr 'Aqab",
          lat: 31.8749,
          lon: 35.2175,
          taCityId: 1926,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירושלים",
          areaNameEn: "Jerusalem",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "ירושלים - מערב",
          englishName: "Jerusalem - West",
          lat: 31.7742,
          lon: 35.1727,
          taCityId: 1922,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירושלים",
          areaNameEn: "Jerusalem",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "ירושלים - מרכז",
          englishName: "Jerusalem - Center",
          lat: 31.7781,
          lon: 35.2164,
          taCityId: 391,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירושלים",
          areaNameEn: "Jerusalem",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "בית זית",
          englishName: "Beit Zayit",
          lat: 31.7831,
          lon: 35.1611,
          taCityId: 466,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירושלים",
          areaNameEn: "Jerusalem",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "בית נקופה",
          englishName: "Beit Nekofa",
          lat: 31.8044,
          lon: 35.1269,
          taCityId: 512,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "הר אדר",
          englishName: "Har Adar",
          lat: 31.8245,
          lon: 35.1297,
          taCityId: 538,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "מבשרת ציון",
          englishName: "Mevasseret Zion",
          lat: 31.8041,
          lon: 35.1579,
          taCityId: 494,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירושלים",
          areaNameEn: "Jerusalem",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "מוצא עילית",
          englishName: "Motza Illit",
          lat: 31.7936,
          lon: 35.157,
          taCityId: 495,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירושלים",
          areaNameEn: "Jerusalem",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "מעלה החמישה",
          englishName: "Ma'aleh HaHamisha",
          lat: 31.8174,
          lon: 35.1094,
          taCityId: 526,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "פנימיית עין כרם",
          englishName: "Ein Kerem Boarding School",
          lat: 31.7788,
          lon: 35.1533,
          taCityId: 465,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירושלים",
          areaNameEn: "Jerusalem",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "צובה",
          englishName: "Tzuba",
          lat: 31.7844,
          lon: 35.118,
          taCityId: 464,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "קריית ענבים",
          englishName: "Kiryat Anavim",
          lat: 31.8099,
          lon: 35.1208,
          taCityId: 513,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "אזור תעשייה הר טוב - צרעה",
          englishName: "Har Tuv - Tzora Industrial Zone",
          lat: 31.7728,
          lon: 34.9981,
          taCityId: 441,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "אשתאול",
          englishName: "Eshtaol",
          lat: 31.7804,
          lon: 35.0101,
          taCityId: 462,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "ביתר עילית",
          englishName: "Beitar Illit",
          lat: 31.701,
          lon: 35.1119,
          taCityId: 371,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "יהודה",
          areaNameEn: "Judea",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "גבעון החדשה",
          englishName: "Givon HaHadasha",
          lat: 31.8481,
          lon: 35.1575,
          taCityId: 1949,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירושלים",
          areaNameEn: "Jerusalem",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "גבעת זאב",
          englishName: "Givat Ze'ev",
          lat: 31.8612,
          lon: 35.1673,
          taCityId: 570,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירושלים",
          areaNameEn: "Jerusalem",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "הר גילה",
          englishName: "Har Gilo",
          lat: 31.7221,
          lon: 35.1715,
          taCityId: 402,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "יהודה",
          areaNameEn: "Judea",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "זנוח",
          englishName: "Zanoah",
          lat: 31.7338,
          lon: 34.9994,
          taCityId: 413,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "מחסיה",
          englishName: "Mahsiya",
          lat: 31.7489,
          lon: 35.0073,
          taCityId: 422,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "מסילת ציון",
          englishName: "Mesillat Zion",
          lat: 31.8014,
          lon: 35.0095,
          taCityId: 489,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "נחם",
          englishName: "Naham",
          lat: 31.7665,
          lon: 35.0036,
          taCityId: 442,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "תרום",
          englishName: "Tarom",
          lat: 31.7833,
          lon: 34.9802,
          taCityId: 461,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "אבו גוש",
          englishName: "Abu Gosh",
          lat: 31.8068,
          lon: 35.1103,
          taCityId: 511,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "אבן ספיר",
          englishName: "Even Sapir",
          lat: 31.7625,
          lon: 35.135,
          taCityId: 443,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירושלים",
          areaNameEn: "Jerusalem",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "אורה",
          englishName: "Ora",
          lat: 31.7521,
          lon: 35.1502,
          taCityId: 429,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירושלים",
          areaNameEn: "Jerusalem",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "בית חורון",
          englishName: "Beit Horon",
          lat: 31.8799,
          lon: 35.1241,
          taCityId: 596,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שומרון",
          areaNameEn: "Samaria",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "בית מאיר",
          englishName: "Beit Meir",
          lat: 31.7948,
          lon: 35.0368,
          taCityId: 490,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "בר גיורא",
          englishName: "Bar Giora",
          lat: 31.7297,
          lon: 35.0734,
          taCityId: 400,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "גבעת אסף",
          englishName: "Giv'at Asaf",
          lat: 31.9112,
          lon: 35.2481,
          taCityId: 1891,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שומרון",
          areaNameEn: "Samaria",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "גבעת יערים",
          englishName: "Givat Yearim",
          lat: 31.7861,
          lon: 35.0928,
          taCityId: 474,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "יד השמונה",
          englishName: "Yad HaShmona",
          lat: 31.8095,
          lon: 35.0896,
          taCityId: 509,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "כסלון",
          englishName: "Ksalon",
          lat: 31.7743,
          lon: 35.0482,
          taCityId: 448,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "כפר הנוער קריית יערים",
          englishName: "Kiryat Ye'arim Youth Village",
          lat: 31.8126,
          lon: 35.1049,
          taCityId: 1963,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "מבוא ביתר",
          englishName: "Mevo Beitar",
          lat: 31.7226,
          lon: 35.1067,
          taCityId: 401,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "מטע",
          englishName: "Mata",
          lat: 31.7165,
          lon: 35.0606,
          taCityId: 389,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "נווה אילן",
          englishName: "Neveh Ilan",
          lat: 31.8076,
          lon: 35.0809,
          taCityId: 507,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "נטף",
          englishName: "Nataf",
          lat: 31.8313,
          lon: 35.0696,
          taCityId: 546,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "נס הרים",
          englishName: "Ness Harim",
          lat: 31.7442,
          lon: 35.0594,
          taCityId: 423,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "עין נקובא",
          englishName: "Ein Naqquba",
          lat: 31.7939,
          lon: 35.1197,
          taCityId: 493,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "עין ראפה",
          englishName: "Ein Rafa",
          lat: 31.7906,
          lon: 35.1165,
          taCityId: 475,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "עמינדב",
          englishName: "Aminadav",
          lat: 31.7517,
          lon: 35.1424,
          taCityId: 428,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירושלים",
          areaNameEn: "Jerusalem",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "פסגות",
          englishName: "Psagot",
          lat: 31.9,
          lon: 35.2239,
          taCityId: 1786,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שומרון",
          areaNameEn: "Samaria",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "צור הדסה",
          englishName: "Tzur Hadassa",
          lat: 31.7194,
          lon: 35.097,
          taCityId: 390,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "קריית יערים",
          englishName: "Kiryat Yearim",
          lat: 31.8028,
          lon: 35.0999,
          taCityId: 510,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "רמת רזיאל",
          englishName: "Ramat Raziel",
          lat: 31.7736,
          lon: 35.0744,
          taCityId: 449,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "שואבה",
          englishName: "Shoeva",
          lat: 31.7994,
          lon: 35.079,
          taCityId: 492,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "שורש",
          englishName: "Shoresh",
          lat: 31.7975,
          lon: 35.0653,
          taCityId: 491,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "תל ציון",
          englishName: "Tel Zion",
          lat: 31.8804,
          lon: 35.2391,
          taCityId: 597,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שומרון",
          areaNameEn: "Samaria",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "אעירה השחר",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "בר כוכבא",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "חוות מעלה אהוביה",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "חוות עדן",
          englishName: "Havat Eden",
          lat: 32.4658,
          lon: 35.4866,
          taCityId: 1026,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "בקעת בית שאן",
          areaNameEn: "Beit Sha'an Valley",
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "שדה בועז",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:15:20",
        },
        {
          name: "כפר מנחם",
          englishName: "Kfar Menachem",
          lat: 31.7321,
          lon: 34.8351,
          taCityId: 397,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:27",
        },
        {
          name: "תחנת רכבת קריית מלאכי - יואב",
          englishName: "Kiryat Mal'akhi-Yoav train station",
          lat: 31.7472,
          lon: 34.8221,
          taCityId: 1937,
          alertTypeId: 1,
          countdownSec: 60,
          areaNameHe: "לכיש",
          areaNameEn: "Lakhish",
          timeStamp: "2026-02-28 11:15:27",
        },
        {
          name: "מבוא חורון",
          englishName: "Mevo Horon",
          lat: 31.8496,
          lon: 35.035,
          taCityId: 554,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "ירקון",
          areaNameEn: "Yarkon",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "נוף איילון, שעלבים",
          englishName: null,
          lat: null,
          lon: null,
          taCityId: null,
          alertTypeId: 1,
          countdownSec: null,
          areaNameHe: null,
          areaNameEn: null,
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "אביעזר",
          englishName: "Aviezer",
          lat: 31.682,
          lon: 35.0188,
          taCityId: 359,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "אדרת",
          englishName: "Aderet",
          lat: 31.6597,
          lon: 34.9944,
          taCityId: 339,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "אלון שבות",
          englishName: "Alon Shvut",
          lat: 31.6549,
          lon: 35.1253,
          taCityId: 341,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "יהודה",
          areaNameEn: "Judea",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "אלעזר",
          englishName: "Elazar",
          lat: 31.6597,
          lon: 35.1431,
          taCityId: 351,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "יהודה",
          areaNameEn: "Judea",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "אפרת",
          englishName: "Efrat",
          lat: 31.6536,
          lon: 35.1499,
          taCityId: 329,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "יהודה",
          areaNameEn: "Judea",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "בית עוזיאל",
          englishName: "Beit Uziel",
          lat: 31.8701,
          lon: 34.9049,
          taCityId: 578,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "השפלה",
          areaNameEn: "Shfela (Lowlands)",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "בית שמש",
          englishName: "Beit Shemesh",
          lat: 31.747,
          lon: 34.9881,
          taCityId: 412,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "בקוע",
          englishName: "Beko'a",
          lat: 31.8279,
          lon: 34.9247,
          taCityId: 536,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "בת עין",
          englishName: "Bat Ayin",
          lat: 31.6577,
          lon: 35.1011,
          taCityId: 340,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "יהודה",
          areaNameEn: "Judea",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "גבעות עדן",
          englishName: "Giv'ot Eden",
          lat: 31.6622,
          lon: 35.0139,
          taCityId: 350,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "גיזו",
          englishName: "Gizo",
          lat: 31.8056,
          lon: 34.9397,
          taCityId: 505,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "הראל",
          englishName: "Harel",
          lat: 31.80944,
          lon: 34.94903,
          taCityId: 506,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "חולדה",
          englishName: "Hulda",
          lat: 31.8321,
          lon: 34.8815,
          taCityId: 535,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "השפלה",
          areaNameEn: "Shfela (Lowlands)",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "טל שחר",
          englishName: "Tal Shachar",
          lat: 31.8044,
          lon: 34.9033,
          taCityId: 486,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "יסודות",
          englishName: "Yesodot",
          lat: 31.8158,
          lon: 34.8656,
          taCityId: 522,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "השפלה",
          areaNameEn: "Shfela (Lowlands)",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "ישעי",
          englishName: "Yish'i",
          lat: 31.753,
          lon: 34.9626,
          taCityId: 427,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "כפר אוריה",
          englishName: "Kfar Uriah",
          lat: 31.7934,
          lon: 34.9448,
          taCityId: 473,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "כפר בן נון",
          englishName: "Kfar Bin Nun",
          lat: 31.8617,
          lon: 34.9472,
          taCityId: 562,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "השפלה",
          areaNameEn: "Shfela (Lowlands)",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "כרמי יוסף",
          englishName: "Karmei Yossef",
          lat: 31.848,
          lon: 34.9213,
          taCityId: 553,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "השפלה",
          areaNameEn: "Shfela (Lowlands)",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "לטרון",
          englishName: "Latrun",
          lat: 31.8369,
          lon: 34.9772,
          taCityId: 545,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "מזכרת בתיה",
          englishName: "Mazkeret Batya",
          lat: 31.8532,
          lon: 34.8424,
          taCityId: 534,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "השפלה",
          areaNameEn: "Shfela (Lowlands)",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "מיני ישראל - נחשון",
          englishName: "Mini Israel - Nachshon",
          lat: 31.8425,
          lon: 34.9685,
          taCityId: 1956,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "משמר איילון",
          englishName: "Mishmar Ayalon",
          lat: 31.8725,
          lon: 34.9433,
          taCityId: 580,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "השפלה",
          areaNameEn: "Shfela (Lowlands)",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "משמר דוד",
          englishName: "Mishmar David",
          lat: 31.8236,
          lon: 34.9007,
          taCityId: 524,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "השפלה",
          areaNameEn: "Shfela (Lowlands)",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "נווה דניאל",
          englishName: "Neveh Daniel",
          lat: 31.6763,
          lon: 35.1433,
          taCityId: 361,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "יהודה",
          areaNameEn: "Judea",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "נווה מיכאל - רוגלית",
          englishName: "Neveh Michael (Rogalit)",
          lat: 31.6728,
          lon: 35.0037,
          taCityId: 355,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "נווה שלום",
          englishName: "Neveh Shalom",
          lat: 31.8174,
          lon: 34.9783,
          taCityId: 525,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "נחשון",
          englishName: "Nachshon",
          lat: 31.8316,
          lon: 34.956,
          taCityId: 537,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "נצר חזני",
          englishName: "Netzer Hazani",
          lat: 31.8214,
          lon: 34.8626,
          taCityId: 523,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "השפלה",
          areaNameEn: "Shfela (Lowlands)",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "נתיב הל''ה",
          englishName: "Netiv HaLamed-Heh",
          lat: 31.687184,
          lon: 34.982523,
          taCityId: 370,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "פדיה",
          englishName: "Pdaya",
          lat: 31.8578,
          lon: 34.8838,
          taCityId: 561,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "השפלה",
          areaNameEn: "Shfela (Lowlands)",
          timeStamp: "2026-02-28 11:15:29",
        },
        {
          name: "צלפון",
          englishName: "Tzalfon",
          lat: 31.8056,
          lon: 34.9318,
          taCityId: 487,
          alertTypeId: 1,
          countdownSec: 90,
          areaNameHe: "שפלת יהודה",
          areaNameEn: "Shfelat Yehuda",
          timeStamp: "2026-02-28 11:15:29",
        },
      ],
    };

    alerts.alerts.forEach((alert) => {
      RealTimeAlertManager.alertQueue.push(alert);
    });

    RealTimeAlertManager.processAlert(this.processRealTimeAlert);
  };

  /*
   * Processes a single real-time alert by showing it in the UI
   */
  processRealTimeAlert = (alert, isLastAlert) => {
    const newMostRecentAlerts = [...this.state.mostRecentAlerts];
    // Add alert to top of alert list
    alert.forEach((a) => newMostRecentAlerts.unshift(a));

    // Maintain a max of Utilities.MAX_RECENT_ALERTS most recent alerts by removing the oldest
    if (newMostRecentAlerts.length >= Utilities.MAX_RECENT_ALERTS) {
      newMostRecentAlerts.pop();
    }

    this.setState({
      realTimeAlert: alert,
      isAlertMode: true,
      mostRecentAlerts: newMostRecentAlerts,
      isLastAlertOfBatch: isLastAlert,
    });
    if (isLastAlert) {
      setTimeout(() => {
        this.setState({
          isAlertMode: false,
        });
      }, Utilities.REAL_TIME_ALERT_THROTTLE_DURATION);
    }

    Tracking.alertModeOnEvent();
  };

  handleScroll = (e) => {
    const vh80 = window.innerHeight * 0.9;
    this.setState({
      showStickyHeader: window.scrollY > Math.floor(vh80) ? true : false,
    });
  };

  handleOnTwitterShareText = (twitterShareText) => {
    this.setState({ twitterShareText });
  };

  handleOnAlertLocationClick = (alert) => this.setState({ mapFocus: alert });

  render() {
    return (
      <div className={"pageContainer"}>
        <HeaderContainer
          alertClient={AlertClient}
          isAlertMode={this.state.isAlertMode}
          realTimeAlert={this.state.realTimeAlert}
          realTimeAlertCache={this.state.realTimeAlertCache}
          isLastAlertOfBatch={this.state.isLastAlertOfBatch}
          onTwitterShareText={this.handleOnTwitterShareText}
        />
        <StickyHeader
          showStickyHeader={this.state.showStickyHeader}
          isAlertMode={this.state.isAlertMode}
          realTimeAlert={this.state.realTimeAlert}
          twitterShareText={this.state.twitterShareText}
        />
        <SupportUs />
        {(this.state.alerts48HrsAgo.length > 0 ||
          this.state.mostRecentAlerts.length > 0) && (
          <section className="section mostRecentAlerts">
            <Row justify="space-around" align="middle">
              {process.env.REACT_APP_SHOULD_SHOW_MAP === "true" ? (
                <>
                  <Col xs={24} lg={12}>
                    <MostRecentAlerts
                      alerts={[
                        ...this.state.mostRecentAlerts,
                        ...this.state.alerts48HrsAgo,
                      ]}
                      onAlertLocationClick={this.handleOnAlertLocationClick}
                    />
                  </Col>
                  <Col xs={24} lg={12}>
                    <RecentAlertsMap
                      alerts48HrsAgo={this.state.alerts48HrsAgo}
                      mostRecentAlerts={this.state.mostRecentAlerts}
                      mapFocus={this.state.mapFocus}
                    />
                  </Col>
                </>
              ) : (
                <>
                  <Col xs={24}>
                    <MostRecentAlerts
                      alerts={this.state.mostRecentAlerts}
                      onAlertLocationClick={this.handleOnAlertLocationClick}
                    />
                  </Col>
                </>
              )}
            </Row>
            {/* <TimeToShelter alerts={this.state.mostRecentAlerts} /> */}
          </section>
        )}
        <OperationLionsRoar alertsClient={AlertClient} />
        <OperationSwordsOfIron alertsClient={AlertClient} />
        {/* <Social /> */}
        {/* <LocationDistance /> */}
        <PreviousOperations alertsClient={AlertClient} />
        <FAQ />
        <SupportUs />
        <Footer twitterShareText={this.state.twitterShareText} />
      </div>
    );
  }
}

export default App;
