const MAP_STYLE = {
  version: 8,
  name: "Dark Matter",
  metadata: { "maputnik:renderer": "mbgljs" },
  sources: {
    carto: {
      type: "vector",
      url: "https://tiles.basemaps.cartocdn.com/vector/carto.streets/v1/tiles.json",
    },
  },
  sprite: "https://tiles.basemaps.cartocdn.com/gl/dark-matter-gl-style/sprite",
  glyphs: "https://tiles.basemaps.cartocdn.com/fonts/{fontstack}/{range}.pbf",
  layers: [
    {
      id: "background",
      type: "background",
      layout: { visibility: "visible" },
      paint: { "background-color": "#292929", "background-opacity": 1 },
    },
    {
      id: "landcover",
      type: "fill",
      source: "carto",
      "source-layer": "landcover",
      filter: [
        "any",
        ["==", "class", "wood"],
        ["==", "class", "grass"],
        ["==", "subclass", "recreation_ground"],
      ],
      paint: {
        "fill-color": {
          stops: [
            [8, "#292929"],
            [9, "#292929"],
            [11, "#272525"],
            [13, "#272525"],
            [15, "#292929"],
          ],
        },
        "fill-opacity": 1,
      },
    },
    {
      id: "landuse_residential",
      type: "fill",
      source: "carto",
      "source-layer": "landuse",
      minzoom: 6,
      filter: ["any", ["==", "class", "residential"]],
      paint: {
        "fill-color": {
          stops: [
            [11, "#272525"],
            [13, "rgba(41, 41, 41, 0.3)"],
            [15, "rgba(41, 41, 41, 0.25)"],
            [16, "rgba(41, 41, 41, 0.15)"],
          ],
        },
        "fill-opacity": {
          stops: [
            [6, 0.6],
            [9, 1],
          ],
        },
      },
    },
    {
      id: "landuse",
      type: "fill",
      source: "carto",
      "source-layer": "landuse",
      filter: ["any", ["==", "class", "cemetery"], ["==", "class", "stadium"]],
      paint: {
        "fill-color": "#1F1F1F",
      },
    },
    {
      id: "water",
      type: "fill",
      source: "carto",
      "source-layer": "water",
      minzoom: 0,
      maxzoom: 24,
      filter: ["all", ["==", "$type", "Polygon"]],
      layout: { visibility: "visible" },
      paint: {
        "fill-color": "#1F1F1F",
        "fill-antialias": true,
        "fill-translate-anchor": "map",
        "fill-opacity": 1,
      },
    },

    // Roads
    {
      id: "road_service_case",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 15,
      maxzoom: 24,
      filter: ["all", ["==", "class", "service"], ["!has", "brunnel"]],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [15, 1],
            [16, 3],
            [17, 6],
            [18, 8],
          ],
        },
        "line-opacity": 1,
        "line-color": "#3D3D3D",
      },
    },
    {
      id: "road_minor_case",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 13,
      maxzoom: 24,
      filter: ["all", ["==", "class", "minor"], ["!has", "brunnel"]],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [11, 0.5],
            [12, 0.5],
            [14, 2],
            [15, 3],
            [16, 4.3],
            [17, 10],
            [18, 14],
          ],
        },
        "line-opacity": 1,
        "line-color": {
          stops: [
            [13, "#3D3D3D"],
            [15.7, "#3D3D3D"],
            [16, "#3D3D3D"],
          ],
        },
      },
    },
    {
      id: "road_pri_case_ramp",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 12,
      maxzoom: 24,
      filter: ["all", ["==", "class", "primary"], ["==", "ramp", 1]],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [12, 2],
            [13, 3],
            [14, 4],
            [15, 5],
            [16, 8],
            [17, 10],
          ],
        },
        "line-opacity": {
          stops: [
            [5, 0.5],
            [7, 1],
          ],
        },
        "line-color": "#3D3D3D",
      },
    },
    {
      id: "road_trunk_case_ramp",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 12,
      maxzoom: 24,
      filter: ["all", ["==", "class", "trunk"], ["==", "ramp", 1]],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [12, 2],
            [13, 3],
            [14, 4],
            [15, 5],
            [16, 8],
            [17, 10],
          ],
        },
        "line-opacity": 1,
        "line-color": {
          stops: [
            [12, "#3D3D3D"],
            [14, "#3D3D3D"],
          ],
        },
      },
    },
    {
      id: "road_mot_case_ramp",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 12,
      maxzoom: 24,
      filter: ["all", ["==", "class", "motorway"], ["==", "ramp", 1]],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [12, 2],
            [13, 3],
            [14, 4],
            [15, 5],
            [16, 8],
            [17, 10],
          ],
        },
        "line-opacity": 1,
        "line-color": {
          stops: [
            [12, "#3D3D3D"],
            [14, "#3D3D3D"],
          ],
        },
      },
    },
    {
      id: "road_sec_case_noramp",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 11,
      maxzoom: 24,
      filter: [
        "all",
        ["in", "class", "secondary", "tertiary"],
        ["!has", "brunnel"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [11, 0.9],
            [12, 1.5],
            [13, 3],
            [14, 5],
            [15, 6],
            [16, 8],
            [17, 12],
            [18, 16],
          ],
        },
        "line-opacity": 1,
        "line-color": {
          stops: [
            [11, "#3D3D3D"],
            [12.99, "#3D3D3D"],
            [13, "#3D3D3D"],
          ],
        },
      },
    },
    {
      id: "road_pri_case_noramp",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 7,
      maxzoom: 24,
      filter: [
        "all",
        ["==", "class", "primary"],
        ["!=", "ramp", 1],
        ["!has", "brunnel"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [6, 0.5],
            [7, 0.8],
            [8, 1],
            [11, 3],
            [13, 4],
            [14, 6],
            [15, 8],
            [16, 10],
            [17, 14],
            [18, 18],
          ],
        },
        "line-opacity": {
          stops: [
            [5, 0.5],
            [7, 1],
          ],
        },
        "line-color": {
          stops: [
            [7, "#3D3D3D"],
            [12, "#3D3D3D"],
          ],
        },
      },
    },
    {
      id: "road_trunk_case_noramp",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 5,
      maxzoom: 24,
      filter: [
        "all",
        ["==", "class", "trunk"],
        ["!=", "ramp", 1],
        ["!has", "brunnel"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [6, 0.5],
            [7, 0.8],
            [8, 1],
            [11, 3],
            [13, 4],
            [14, 6],
            [15, 8],
            [16, 10],
            [17, 14],
            [18, 18],
          ],
        },
        "line-opacity": {
          stops: [
            [5, 0.5],
            [7, 1],
          ],
        },
        "line-color": {
          stops: [
            [5, "#3D3D3D"],
            [12, "#3D3D3D"],
          ],
        },
      },
    },
    {
      id: "road_mot_case_noramp",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 5,
      maxzoom: 24,
      filter: [
        "all",
        ["==", "class", "motorway"],
        ["!=", "ramp", 1],
        ["!has", "brunnel"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [6, 0.5],
            [7, 0.7],
            [8, 0.8],
            [11, 3],
            [12, 4],
            [13, 5],
            [14, 7],
            [15, 9],
            [16, 11],
            [17, 13],
            [18, 22],
          ],
        },
        "line-opacity": {
          stops: [
            [6, 0.5],
            [7, 1],
          ],
        },
        "line-color": {
          stops: [
            [5, "#3D3D3D"],
            [12, "#3D3D3D"],
          ],
        },
      },
    },
    {
      id: "road_path",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 15,
      maxzoom: 24,
      filter: ["all", ["in", "class", "path", "track"], ["!has", "brunnel"]],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [15, 0.5],
            [16, 1],
            [18, 3],
          ],
        },
        "line-opacity": 1,
        "line-color": "#3D3D3D",
        "line-dasharray": {
          stops: [
            [15, [2, 2]],
            [18, [3, 3]],
          ],
        },
      },
    },
    {
      id: "road_service_fill",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 15,
      maxzoom: 24,
      filter: ["all", ["==", "class", "service"], ["!has", "brunnel"]],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [15, 2],
            [16, 2],
            [17, 4],
            [18, 6],
          ],
        },
        "line-opacity": 1,
        "line-color": "#3D3D3D",
      },
    },
    {
      id: "road_minor_fill",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 15,
      maxzoom: 24,
      filter: ["all", ["==", "class", "minor"], ["!has", "brunnel"]],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [15, 3],
            [16, 4],
            [17, 8],
            [18, 12],
          ],
        },
        "line-opacity": 1,
        "line-color": "#3D3D3D",
      },
    },
    {
      id: "road_pri_fill_ramp",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 12,
      maxzoom: 24,
      filter: ["all", ["==", "class", "primary"], ["==", "ramp", 1]],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [12, 1],
            [13, 1.5],
            [14, 2],
            [15, 3],
            [16, 6],
            [17, 8],
          ],
        },
        "line-opacity": 1,
        "line-color": "#3D3D3D",
      },
    },
    {
      id: "road_trunk_fill_ramp",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 12,
      maxzoom: 24,
      filter: ["all", ["==", "class", "trunk"], ["==", "ramp", 1]],
      layout: { "line-cap": "square", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [12, 1],
            [13, 1.5],
            [14, 2],
            [15, 3],
            [16, 6],
            [17, 8],
          ],
        },
        "line-opacity": 1,
        "line-color": "#3D3D3D",
      },
    },
    {
      id: "road_mot_fill_ramp",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 12,
      maxzoom: 24,
      filter: ["all", ["==", "class", "motorway"], ["==", "ramp", 1]],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [12, 1],
            [13, 1.5],
            [14, 2],
            [15, 3],
            [16, 6],
            [17, 8],
          ],
        },
        "line-opacity": 1,
        "line-color": "#3D3D3D",
      },
    },
    {
      id: "road_sec_fill_noramp",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 13,
      maxzoom: 24,
      filter: [
        "all",
        ["in", "class", "secondary", "tertiary"],
        ["!has", "brunnel"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [11, 2],
            [13, 2],
            [14, 3],
            [15, 4],
            [16, 6],
            [17, 10],
            [18, 14],
          ],
        },
        "line-opacity": 1,
        "line-color": "#3D3D3D",
      },
    },
    {
      id: "road_pri_fill_noramp",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 10,
      maxzoom: 24,
      filter: [
        "all",
        ["==", "class", "primary"],
        ["!=", "ramp", 1],
        ["!has", "brunnel"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [10, 0.3],
            [13, 2],
            [14, 4],
            [15, 6],
            [16, 8],
            [17, 12],
            [18, 16],
          ],
        },
        "line-opacity": 1,
        "line-color": "#3D3D3D",
      },
    },
    {
      id: "road_trunk_fill_noramp",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 10,
      maxzoom: 24,
      filter: [
        "all",
        ["==", "class", "trunk"],
        ["!=", "ramp", 1],
        ["!has", "brunnel"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [11, 1],
            [13, 2],
            [14, 4],
            [15, 6],
            [16, 8],
            [17, 12],
            [18, 16],
          ],
        },
        "line-opacity": 1,
        "line-color": "#3D3D3D",
      },
    },
    {
      id: "road_mot_fill_noramp",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 10,
      maxzoom: 24,
      filter: [
        "all",
        ["==", "class", "motorway"],
        ["!=", "ramp", 1],
        ["!has", "brunnel"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-width": {
          stops: [
            [10, 1],
            [12, 2],
            [13, 3],
            [14, 5],
            [15, 7],
            [16, 9],
            [17, 11],
            [18, 20],
          ],
        },
        "line-opacity": 1,
        "line-color": "#3D3D3D",
      },
    },
    {
      id: "rail",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 13,
      filter: ["all", ["==", "class", "rail"], ["!=", "brunnel", "tunnel"]],
      layout: { visibility: "visible", "line-join": "round" },
      paint: {
        "line-color": "#1a1a1a",
        "line-width": {
          base: 1.3,
          stops: [
            [13, 0.5],
            [14, 1],
            [15, 1],
            [16, 3],
            [21, 7],
          ],
        },
      },
    },
    {
      id: "rail_dash",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 15,
      filter: ["all", ["==", "class", "rail"], ["!=", "brunnel", "tunnel"]],
      layout: { visibility: "visible", "line-join": "round" },
      paint: {
        "line-color": "#111",
        "line-width": {
          base: 1.3,
          stops: [
            [15, 0.5],
            [16, 1],
            [20, 5],
          ],
        },
        "line-dasharray": {
          stops: [
            [15, [5, 5]],
            [16, [6, 6]],
          ],
        },
      },
    },

    // Buildings
    {
      id: "building-top",
      type: "fill",
      source: "carto",
      "source-layer": "building",
      layout: { visibility: "visible" },
      paint: {
        "fill-translate": {
          base: 1,
          stops: [
            [14, [0, 0]],
            [16, [-2, -2]],
          ],
        },
        "fill-color": {
          stops: [
            [13, "#3D3D3D"],
            [15, "#1F1F1F"],
          ],
        },
        "fill-opacity": {
          base: 1,
          stops: [
            [13, 0],
            [16, 1],
          ],
        },
      },
    },

    {
      id: "boundary_country_inner",
      type: "line",
      source: "carto",
      "source-layer": "boundary",
      minzoom: 0,
      filter: ["all", ["==", "admin_level", 2], ["==", "maritime", 0]],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": {
          stops: [
            [4, "rgba(92, 94, 94, 1)"],
            [5, "rgba(96, 96, 96, 1)"],
            [6, "rgba(102, 102, 102, 1)"],
          ],
        },
        "line-opacity": 1,
        "line-width": {
          stops: [
            [3, 1],
            [6, 1.5],
          ],
        },
        "line-offset": 0,
      },
    },

    // Places (symbol)
    {
      id: "place_suburbs",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 12,
      maxzoom: 16,
      filter: ["all", ["==", "class", "suburb"]],
      layout: {
        "text-field": "{name_en}",
        "text-font": [
          "Montserrat Regular",
          "Open Sans Regular",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": {
          stops: [
            [12, 9],
            [13, 10],
            [14, 11],
            [15, 12],
            [16, 13],
          ],
        },
        "icon-image": "",
        "icon-offset": [16, 0],
        "text-anchor": "center",
        "icon-size": 1,
        "text-max-width": 10,
        "text-keep-upright": true,
        "text-offset": [0.2, 0.2],
        "text-transform": {
          stops: [
            [8, "none"],
            [12, "uppercase"],
          ],
        },
      },
      paint: {
        "text-color": "#666",
        "icon-color": "#666",
        "icon-translate-anchor": "map",
        "text-halo-color": "#222",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_villages",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 10,
      maxzoom: 16,
      filter: ["all", ["==", "class", "village"]],
      layout: {
        "text-field": "{name_en}",
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": {
          stops: [
            [10, 9],
            [12, 10],
            [13, 11],
            [14, 12],
            [16, 13],
          ],
        },
        "icon-image": "",
        "icon-offset": [16, 0],
        "text-anchor": "center",
        "icon-size": 1,
        "text-max-width": 10,
        "text-keep-upright": true,
        "text-offset": [0.2, 0.2],
        "text-transform": "none",
      },
      paint: {
        "text-color": "rgba(154, 153, 153, 1)",
        "icon-color": "#666",
        "icon-translate-anchor": "map",
        "text-halo-color": "#222",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_town",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 8,
      maxzoom: 14,
      filter: ["all", ["==", "class", "town"]],
      layout: {
        "text-field": "{name_en}",
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": {
          stops: [
            [8, 10],
            [9, 10],
            [10, 11],
            [13, 14],
            [14, 15],
          ],
        },
        "icon-image": "",
        "icon-offset": [16, 0],
        "text-anchor": "center",
        "icon-size": 1,
        "text-max-width": 10,
        "text-keep-upright": true,
        "text-offset": [0.2, 0.2],
        "text-transform": "none",
      },
      paint: {
        "text-color": "rgba(166, 166, 166, 0.5)",
        "icon-color": "#666",
        "icon-translate-anchor": "map",
        "text-halo-color": "#222",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_country_2",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 3,
      maxzoom: 10,
      filter: [
        "all",
        ["==", "class", "country"],
        [">=", "rank", 3],
        ["has", "iso_a2"],
      ],
      layout: {
        "text-field": "{name_en}",
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": {
          stops: [
            [3, 10],
            [5, 11],
            [6, 12],
            [7, 13],
            [8, 14],
          ],
        },
        "text-transform": "uppercase",
      },
      paint: {
        "text-color": "#A6A6A6",
        "text-halo-color": "#111",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_country_1",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 2,
      maxzoom: 7,
      filter: ["all", ["==", "class", "country"], ["<=", "rank", 2]],
      layout: {
        "text-field": "{name_en}",
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": {
          stops: [
            [3, 11],
            [4, 12],
            [5, 13],
            [6, 14],
          ],
        },
        "text-transform": "uppercase",
        "text-max-width": {
          stops: [
            [2, 6],
            [3, 6],
            [4, 9],
            [5, 12],
          ],
        },
      },
      paint: {
        "text-color": "#A6A6A6",
        "text-halo-color": "#111",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_state",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 5,
      maxzoom: 10,
      filter: ["all", ["==", "class", "state"], ["<=", "rank", 4]],
      layout: {
        "text-field": "{name_en}",
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": {
          stops: [
            [5, 12],
            [7, 14],
          ],
        },
        "text-transform": "uppercase",
        "text-max-width": 9,
      },
      paint: {
        "text-color": "#A6A6A6",
        "text-halo-color": "#111",
        "text-halo-width": 0,
      },
    },
    {
      id: "place_continent",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 0,
      maxzoom: 2,
      filter: ["all", ["==", "class", "continent"]],
      layout: {
        "text-field": "{name_en}",
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-transform": "uppercase",
        "text-size": 14,
        "text-letter-spacing": 0.1,
        "text-max-width": 9,
        "text-justify": "center",
        "text-keep-upright": false,
      },
      paint: {
        "text-color": "#A6A6A6",
        "text-halo-color": "#111",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_city_r6",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 8,
      maxzoom: 15,
      filter: ["all", ["==", "class", "city"], [">=", "rank", 6]],
      layout: {
        "text-field": "{name_en}",
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": {
          stops: [
            [8, 12],
            [9, 13],
            [10, 14],
            [13, 17],
            [14, 20],
          ],
        },
        "icon-image": "",
        "icon-offset": [16, 0],
        "text-anchor": "center",
        "icon-size": 1,
        "text-max-width": 10,
        "text-keep-upright": true,
        "text-offset": [0.2, 0.2],
        "text-transform": "uppercase",
      },
      paint: {
        "text-color": "#A6A6A6",
        "icon-color": "#666",
        "icon-translate-anchor": "map",
        "text-halo-color": "#222",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_city_r5",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 8,
      maxzoom: 15,
      filter: [
        "all",
        ["==", "class", "city"],
        [">=", "rank", 0],
        ["<=", "rank", 5],
      ],
      layout: {
        "text-field": "{name_en}",
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": {
          stops: [
            [8, 14],
            [10, 16],
            [13, 19],
            [14, 22],
          ],
        },
        "icon-image": "",
        "icon-offset": [16, 0],
        "text-anchor": "center",
        "icon-size": 1,
        "text-max-width": 10,
        "text-keep-upright": true,
        "text-offset": [0.2, 0.2],
        "text-transform": "uppercase",
      },
      paint: {
        "text-color": "#A6A6A6",
        "icon-color": "#666",
        "icon-translate-anchor": "map",
        "text-halo-color": "#222",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_city_dot_r7",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 6,
      maxzoom: 7,
      filter: ["all", ["==", "class", "city"], ["<=", "rank", 7]],
      layout: {
        "text-field": "{name_en}",
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": 12,
        "icon-image": "circle-11",
        "icon-offset": [16, 5],
        "text-anchor": "right",
        "icon-size": 0.4,
        "text-max-width": 8,
        "text-keep-upright": true,
        "text-offset": [0.2, 0.2],
      },
      paint: {
        "text-color": "#A6A6A6",
        "icon-color": "rgba(94, 105, 106, 1)",
        "icon-translate-anchor": "map",
        "text-halo-color": "#222",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_city_dot_r4",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 5,
      maxzoom: 7,
      filter: ["all", ["==", "class", "city"], ["<=", "rank", 4]],
      layout: {
        "text-field": "{name_en}",
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": 12,
        "icon-image": "circle-11",
        "icon-offset": [16, 5],
        "text-anchor": "right",
        "icon-size": 0.4,
        "text-max-width": 8,
        "text-keep-upright": true,
        "text-offset": [0.2, 0.2],
      },
      paint: {
        "text-color": "#A6A6A6",
        "icon-color": "#666",
        "icon-translate-anchor": "map",
        "text-halo-color": "#222",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_city_dot_r2",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 4,
      maxzoom: 7,
      filter: ["all", ["==", "class", "city"], ["<=", "rank", 2]],
      layout: {
        "text-field": "{name_en}",
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": 12,
        "icon-image": "circle-11",
        "icon-offset": [16, 5],
        "text-anchor": "right",
        "icon-size": 0.4,
        "text-max-width": 8,
        "text-keep-upright": true,
        "text-offset": [0.2, 0.2],
      },
      paint: {
        "text-color": "#A6A6A6",
        "icon-color": "rgba(131, 164, 189, 1)",
        "icon-translate-anchor": "map",
        "text-halo-color": "#222",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_city_dot_z7",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 7,
      maxzoom: 8,
      filter: [
        "all",
        ["!has", "capital"],
        ["!in", "class", "country", "state"],
      ],
      layout: {
        "text-field": "{name_en}",
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": 12,
        "icon-image": "circle-11",
        "icon-offset": [16, 5],
        "text-anchor": "right",
        "icon-size": 0.4,
        "text-max-width": 8,
        "text-keep-upright": true,
        "text-offset": [0.2, 0.2],
      },
      paint: {
        "text-color": "#A6A6A6",
        "icon-color": "rgba(113, 128, 147, 1)",
        "icon-translate-anchor": "map",
        "text-halo-color": "#222",
        "text-halo-width": 1,
      },
    },
    {
      id: "place_capital_dot_z7",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 7,
      maxzoom: 8,
      filter: ["all", [">", "capital", 0]],
      layout: {
        "text-field": "{name_en}",
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": 12,
        "icon-image": "circle-11",
        "icon-offset": [16, 5],
        "text-anchor": "right",
        "icon-size": 0.4,
        "text-max-width": 8,
        "text-keep-upright": true,
        "text-offset": [0.2, 0.2],
        "text-transform": "uppercase",
      },
      paint: {
        "text-color": "#A6A6A6",
        "icon-color": "#666",
        "icon-translate-anchor": "map",
        "text-halo-color": "#222",
        "text-halo-width": 1,
      },
    },
    {
      id: "poi_stadium",
      type: "symbol",
      source: "carto",
      "source-layer": "poi",
      minzoom: 15,
      filter: [
        "all",
        ["in", "class", "stadium", "cemetery", "attraction"],
        ["<=", "rank", 3],
      ],
      layout: {
        "text-field": "{name}",
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": {
          stops: [
            [15, 8],
            [17, 9],
            [18, 10],
          ],
        },
        "text-transform": "uppercase",
      },
      paint: {
        "text-color": "#515151",
        "text-halo-color": "#151515",
        "text-halo-width": 1,
      },
    },
    {
      id: "poi_park",
      type: "symbol",
      source: "carto",
      "source-layer": "poi",
      minzoom: 15,
      filter: ["all", ["==", "class", "park"]],
      layout: {
        "text-field": "{name}",
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": {
          stops: [
            [15, 8],
            [17, 9],
            [18, 10],
          ],
        },
        "text-transform": "uppercase",
      },
      paint: {
        "text-color": "#515151",
        "text-halo-color": "#151515",
        "text-halo-width": 1,
      },
    },

    // Road Names
    {
      id: "roadname_minor",
      type: "symbol",
      source: "carto",
      "source-layer": "transportation_name",
      minzoom: 16,
      filter: ["all", ["in", "class", "minor", "service"]],
      layout: {
        "symbol-placement": "line",
        "text-font": [
          "Montserrat Regular",
          "Open Sans Regular",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": 9,
        "text-field": "{name}",
        "symbol-avoid-edges": false,
        "symbol-spacing": 200,
        "text-pitch-alignment": "auto",
        "text-rotation-alignment": "auto",
        "text-justify": "center",
      },
      paint: {
        "text-color": "rgba(181, 180, 180, 1)",
        "text-halo-color": "#111",
        "text-halo-width": 1,
      },
    },
    {
      id: "roadname_sec",
      type: "symbol",
      source: "carto",
      "source-layer": "transportation_name",
      minzoom: 15,
      filter: ["all", ["in", "class", "secondary", "tertiary"]],
      layout: {
        "symbol-placement": "line",
        "text-font": [
          "Montserrat Regular",
          "Open Sans Regular",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": {
          stops: [
            [15, 9],
            [16, 11],
            [18, 12],
          ],
        },
        "text-field": "{name}",
        "symbol-avoid-edges": false,
        "symbol-spacing": 200,
        "text-pitch-alignment": "auto",
        "text-rotation-alignment": "auto",
        "text-justify": "center",
      },
      paint: {
        "text-color": "rgba(146, 146, 146, 1)",
        "text-halo-color": "rgba(34, 34, 34, 1)",
        "text-halo-width": 1,
      },
    },
    {
      id: "roadname_pri",
      type: "symbol",
      source: "carto",
      "source-layer": "transportation_name",
      minzoom: 14,
      filter: ["all", ["in", "class", "primary"]],
      layout: {
        "symbol-placement": "line",
        "text-font": [
          "Montserrat Regular",
          "Open Sans Regular",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": {
          stops: [
            [14, 10],
            [15, 10],
            [16, 11],
            [18, 12],
          ],
        },
        "text-field": "{name}",
        "symbol-avoid-edges": false,
        "symbol-spacing": {
          stops: [
            [6, 200],
            [16, 250],
          ],
        },
        "text-pitch-alignment": "auto",
        "text-rotation-alignment": "auto",
        "text-justify": "center",
        "text-letter-spacing": {
          stops: [
            [14, 0],
            [16, 0.2],
          ],
        },
      },
      paint: {
        "text-color": "rgba(189, 189, 189, 1)",
        "text-halo-color": "#111",
        "text-halo-width": 1,
      },
    },
    {
      id: "roadname_major",
      type: "symbol",
      source: "carto",
      "source-layer": "transportation_name",
      minzoom: 13,
      filter: ["all", ["in", "class", "trunk", "motorway"]],
      layout: {
        "symbol-placement": "line",
        "text-font": [
          "Montserrat Regular",
          "Open Sans Regular",
          "Noto Sans Regular",
          "HanWangHeiLight Regular",
          "NanumBarunGothic Regular",
        ],
        "text-size": {
          stops: [
            [14, 10],
            [15, 10],
            [16, 11],
            [18, 12],
          ],
        },
        "text-field": "{name}",
        "symbol-avoid-edges": false,
        "symbol-spacing": {
          stops: [
            [6, 200],
            [16, 250],
          ],
        },
        "text-pitch-alignment": "auto",
        "text-rotation-alignment": "auto",
        "text-justify": "center",
        "text-letter-spacing": {
          stops: [
            [13, 0],
            [16, 0.2],
          ],
        },
      },
      paint: {
        "text-color": "#383838",
        "text-halo-color": "#111",
        "text-halo-width": 1,
      },
    },
  ],
  id: "voyager",
  owner: "Carto",
};

export default MAP_STYLE;
