name: CI + Release

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2

      - name: Install
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build 🔧
        run: npm run build

  release:
    needs: test-and-build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - run: npm ci

      - run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy 🚀
        run: |
          npm install -g gh-pages
          gh-pages -d dist \
            -r https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
